spring:
  profiles:
    active:
      - local
server:
  port: 8083
---
spring:
  profiles: production
withkid:
  firestore:
    keypath: "/usr/share/test-fe856-21f716968770.json"
  api:
    userId:
      uri: http://withkid_auth_server
      port: 8082
---
spring:
  profiles: local
withkid:
  firestore:
    keypath: "C:\\Users\\전찬동\\Downloads\\test-fe856-21f716968770.json"
  api:
    userId:
      uri: http://localhost
      port: 8082
