spring:
  profiles:
    active:
      - local
server:
  port: 8083
---
spring:
  profiles: production
withkid:
  firestore:
    keypath: "/usr/share/firebase/test-fe856-21f716968770.json"
  api:
    uri: https://withkid.tk
    userId:
      port: 8090
    event:
      port: 8081
---
spring:
  profiles: local
withkid:
  firestore:
    keypath: "C:\\Users\\전찬동\\Downloads\\test-fe856-21f716968770.json"
  api:
    uri: http://192.168.99.100
    userId:
      port: 8090
    event:
      port: 8081
